// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: album.proto

package dustin.examples.protobuf;

public final class AlbumProtos {
  private AlbumProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlbumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Album)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>repeated string artist = 2;</code>
     */
    java.util.List<java.lang.String>
        getArtistList();
    /**
     * <code>repeated string artist = 2;</code>
     */
    int getArtistCount();
    /**
     * <code>repeated string artist = 2;</code>
     */
    java.lang.String getArtist(int index);
    /**
     * <code>repeated string artist = 2;</code>
     */
    com.google.protobuf.ByteString
        getArtistBytes(int index);

    /**
     * <code>int32 release_year = 3;</code>
     */
    int getReleaseYear();

    /**
     * <code>repeated string song_title = 4;</code>
     */
    java.util.List<java.lang.String>
        getSongTitleList();
    /**
     * <code>repeated string song_title = 4;</code>
     */
    int getSongTitleCount();
    /**
     * <code>repeated string song_title = 4;</code>
     */
    java.lang.String getSongTitle(int index);
    /**
     * <code>repeated string song_title = 4;</code>
     */
    com.google.protobuf.ByteString
        getSongTitleBytes(int index);
  }
  /**
   * Protobuf type {@code Album}
   */
  public  static final class Album extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Album)
      AlbumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Album.newBuilder() to construct.
    private Album(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Album() {
      title_ = "";
      artist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      releaseYear_ = 0;
      songTitle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Album(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                artist_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              artist_.add(s);
              break;
            }
            case 24: {

              releaseYear_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                songTitle_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              songTitle_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          artist_ = artist_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          songTitle_ = songTitle_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dustin.examples.protobuf.AlbumProtos.internal_static_Album_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dustin.examples.protobuf.AlbumProtos.internal_static_Album_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dustin.examples.protobuf.AlbumProtos.Album.class, dustin.examples.protobuf.AlbumProtos.Album.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTIST_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList artist_;
    /**
     * <code>repeated string artist = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getArtistList() {
      return artist_;
    }
    /**
     * <code>repeated string artist = 2;</code>
     */
    public int getArtistCount() {
      return artist_.size();
    }
    /**
     * <code>repeated string artist = 2;</code>
     */
    public java.lang.String getArtist(int index) {
      return artist_.get(index);
    }
    /**
     * <code>repeated string artist = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArtistBytes(int index) {
      return artist_.getByteString(index);
    }

    public static final int RELEASE_YEAR_FIELD_NUMBER = 3;
    private int releaseYear_;
    /**
     * <code>int32 release_year = 3;</code>
     */
    public int getReleaseYear() {
      return releaseYear_;
    }

    public static final int SONG_TITLE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList songTitle_;
    /**
     * <code>repeated string song_title = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSongTitleList() {
      return songTitle_;
    }
    /**
     * <code>repeated string song_title = 4;</code>
     */
    public int getSongTitleCount() {
      return songTitle_.size();
    }
    /**
     * <code>repeated string song_title = 4;</code>
     */
    public java.lang.String getSongTitle(int index) {
      return songTitle_.get(index);
    }
    /**
     * <code>repeated string song_title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSongTitleBytes(int index) {
      return songTitle_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      for (int i = 0; i < artist_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, artist_.getRaw(i));
      }
      if (releaseYear_ != 0) {
        output.writeInt32(3, releaseYear_);
      }
      for (int i = 0; i < songTitle_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, songTitle_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < artist_.size(); i++) {
          dataSize += computeStringSizeNoTag(artist_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArtistList().size();
      }
      if (releaseYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, releaseYear_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < songTitle_.size(); i++) {
          dataSize += computeStringSizeNoTag(songTitle_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSongTitleList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dustin.examples.protobuf.AlbumProtos.Album)) {
        return super.equals(obj);
      }
      dustin.examples.protobuf.AlbumProtos.Album other = (dustin.examples.protobuf.AlbumProtos.Album) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getArtistList()
          .equals(other.getArtistList());
      result = result && (getReleaseYear()
          == other.getReleaseYear());
      result = result && getSongTitleList()
          .equals(other.getSongTitleList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      if (getArtistCount() > 0) {
        hash = (37 * hash) + ARTIST_FIELD_NUMBER;
        hash = (53 * hash) + getArtistList().hashCode();
      }
      hash = (37 * hash) + RELEASE_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseYear();
      if (getSongTitleCount() > 0) {
        hash = (37 * hash) + SONG_TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getSongTitleList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dustin.examples.protobuf.AlbumProtos.Album parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dustin.examples.protobuf.AlbumProtos.Album prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Album}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Album)
        dustin.examples.protobuf.AlbumProtos.AlbumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dustin.examples.protobuf.AlbumProtos.internal_static_Album_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dustin.examples.protobuf.AlbumProtos.internal_static_Album_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dustin.examples.protobuf.AlbumProtos.Album.class, dustin.examples.protobuf.AlbumProtos.Album.Builder.class);
      }

      // Construct using dustin.examples.protobuf.AlbumProtos.Album.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";

        artist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        releaseYear_ = 0;

        songTitle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dustin.examples.protobuf.AlbumProtos.internal_static_Album_descriptor;
      }

      public dustin.examples.protobuf.AlbumProtos.Album getDefaultInstanceForType() {
        return dustin.examples.protobuf.AlbumProtos.Album.getDefaultInstance();
      }

      public dustin.examples.protobuf.AlbumProtos.Album build() {
        dustin.examples.protobuf.AlbumProtos.Album result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dustin.examples.protobuf.AlbumProtos.Album buildPartial() {
        dustin.examples.protobuf.AlbumProtos.Album result = new dustin.examples.protobuf.AlbumProtos.Album(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          artist_ = artist_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.artist_ = artist_;
        result.releaseYear_ = releaseYear_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          songTitle_ = songTitle_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.songTitle_ = songTitle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dustin.examples.protobuf.AlbumProtos.Album) {
          return mergeFrom((dustin.examples.protobuf.AlbumProtos.Album)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dustin.examples.protobuf.AlbumProtos.Album other) {
        if (other == dustin.examples.protobuf.AlbumProtos.Album.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.artist_.isEmpty()) {
          if (artist_.isEmpty()) {
            artist_ = other.artist_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArtistIsMutable();
            artist_.addAll(other.artist_);
          }
          onChanged();
        }
        if (other.getReleaseYear() != 0) {
          setReleaseYear(other.getReleaseYear());
        }
        if (!other.songTitle_.isEmpty()) {
          if (songTitle_.isEmpty()) {
            songTitle_ = other.songTitle_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSongTitleIsMutable();
            songTitle_.addAll(other.songTitle_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dustin.examples.protobuf.AlbumProtos.Album parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dustin.examples.protobuf.AlbumProtos.Album) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList artist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArtistIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          artist_ = new com.google.protobuf.LazyStringArrayList(artist_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getArtistList() {
        return artist_.getUnmodifiableView();
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public int getArtistCount() {
        return artist_.size();
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public java.lang.String getArtist(int index) {
        return artist_.get(index);
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArtistBytes(int index) {
        return artist_.getByteString(index);
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public Builder setArtist(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArtistIsMutable();
        artist_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public Builder addArtist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArtistIsMutable();
        artist_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public Builder addAllArtist(
          java.lang.Iterable<java.lang.String> values) {
        ensureArtistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, artist_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public Builder clearArtist() {
        artist_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string artist = 2;</code>
       */
      public Builder addArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureArtistIsMutable();
        artist_.add(value);
        onChanged();
        return this;
      }

      private int releaseYear_ ;
      /**
       * <code>int32 release_year = 3;</code>
       */
      public int getReleaseYear() {
        return releaseYear_;
      }
      /**
       * <code>int32 release_year = 3;</code>
       */
      public Builder setReleaseYear(int value) {
        
        releaseYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 release_year = 3;</code>
       */
      public Builder clearReleaseYear() {
        
        releaseYear_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList songTitle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSongTitleIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          songTitle_ = new com.google.protobuf.LazyStringArrayList(songTitle_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSongTitleList() {
        return songTitle_.getUnmodifiableView();
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public int getSongTitleCount() {
        return songTitle_.size();
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public java.lang.String getSongTitle(int index) {
        return songTitle_.get(index);
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSongTitleBytes(int index) {
        return songTitle_.getByteString(index);
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public Builder setSongTitle(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSongTitleIsMutable();
        songTitle_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public Builder addSongTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSongTitleIsMutable();
        songTitle_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public Builder addAllSongTitle(
          java.lang.Iterable<java.lang.String> values) {
        ensureSongTitleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, songTitle_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public Builder clearSongTitle() {
        songTitle_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string song_title = 4;</code>
       */
      public Builder addSongTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSongTitleIsMutable();
        songTitle_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Album)
    }

    // @@protoc_insertion_point(class_scope:Album)
    private static final dustin.examples.protobuf.AlbumProtos.Album DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dustin.examples.protobuf.AlbumProtos.Album();
    }

    public static dustin.examples.protobuf.AlbumProtos.Album getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Album>
        PARSER = new com.google.protobuf.AbstractParser<Album>() {
      public Album parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Album(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Album> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Album> getParserForType() {
      return PARSER;
    }

    public dustin.examples.protobuf.AlbumProtos.Album getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Album_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Album_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013album.proto\"P\n\005Album\022\r\n\005title\030\001 \001(\t\022\016\n" +
      "\006artist\030\002 \003(\t\022\024\n\014release_year\030\003 \001(\005\022\022\n\ns" +
      "ong_title\030\004 \003(\tB\'\n\030dustin.examples.proto" +
      "bufB\013AlbumProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Album_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Album_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Album_descriptor,
        new java.lang.String[] { "Title", "Artist", "ReleaseYear", "SongTitle", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
